name: hello
base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: riscv64
  - build-on: s390x

version: "2.12.1"
summary: GNU Hello
description: GNU hello prints a friendly greeting.

apps:
  hello:
    command: bin/hello
  universe:
    # '"' is not allowed for commands.
    command: bin/hello -g $SAY
    environment:
      SAY: "Hello, universe!"

parts:
  gnu-hello:
    source: https://ftp.gnu.org/gnu/$SNAPCRAFT_PROJECT_NAME/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/
