name: hello
base: core
confinement: strict
grade: stable

version: "2.10"
summary: GNU Hello
description: GNU hello prints a friendly greeting.

apps:
  hello:
    command: bin/hello
    adapter: full
  universe:
    # Create a wrapper to avoid:
    # Failed to generate snap metadata: The specified command
    # 'bin/hello -g "Hello, universe!"' defined in the app 'universe'
    # does not match the pattern expected by snapd.
    # The command must consist only of alphanumeric characters, spaces,
    # and the following special characters: / . _ # : $ -
    command: bin/hello -g "Hello, universe!"
    adapter: legacy

parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/$SNAPCRAFT_PROJECT_NAME/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: autotools
