name: hello
base: core20
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

version: "2.10"
summary: GNU Hello
description: GNU hello prints a friendly greeting.

apps:
  hello:
    command: bin/hello
  universe:
    # '"' is not allowed for commands.
    command: bin/hello -g $SAY
    environment:
      SAY: "Hello, universe!"

parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/$SNAPCRAFT_PROJECT_NAME/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    source-checksum: sha256/31e066137a962676e89f69d1b65382de95a7ef7d914b8cb956f41ea72e0f516b
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/
